spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/library_app
    username: postgres
    password: postgresql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

flyway:
  enabled: true
