apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-backend
  template:
    metadata:
      labels:
        app: library-backend
    spec:
      containers:
        - name: library-backend
          image: michalkrawczyk16/library-backend:latest
          ports:
            - containerPort: 8190
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/library_app"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgresql"
      imagePullSecrets:
        - name: regcred